apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yashwanth14/sample-app:2
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
             configMapKeyRef: 
                 name: backend-config
                 key: port
        - name: DATABASE_URL
          valueFrom:
             configMapKeyRef:
                name: backend-config
                key: database_url

