apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@postgres-service:5432/mydatabase"
